
# Name of website
title: Function of Dreams

# Your name to show in the footer
author: Vaibhav Singh Tomar

# --- List of links in the navigation bar --- #

navbar-links:
  About Me: "aboutme"
  Resources:
    - Learn markdown: "https://www.markdowntutorial.com/"

# --- Logo --- #
avatar: "/assets/img/avatar-icon.png"
round-avatar: true

# --- Footer social media links --- #

social-network-links:
  email: "vst17march@gmail.com"
  github: https://github.com/vstflugel
  linkedin: linkedin.com/in/vaibhav-singh-tomar-99a5201a0




# Excerpt word length - Truncate the excerpt of each post on the feed page to the specified number of words
excerpt_length: 50

# Whether or not to show an excerpt for every blog post in the feed page
feed_show_excerpt: true

# Whether or not to show a list of tags below each post preview in the feed page
feed_show_tags: true

# Add a search button to the navbar
post_search: true


# --- Colours / background image --- #

navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"


date_format: "%B %-d, %Y"



# Output options 
timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values 
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

# Exclude these files from production site
exclude:

  - CNAME
  - README.md
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap

